# POSTTEST 7
# TENSORFLOW

### Import Library

In [1]:
import tensorflow as tf
import numpy as np

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [50]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=4)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8579795 ,  0.6959921 , -0.13605411, -1.2646562 ,  0.8854719 ],
       [ 0.47240213,  1.0577366 , -2.139898  ,  0.3358737 , -0.7004127 ],
       [-1.2003378 ,  1.545108  ,  0.6954568 ,  0.8174248 ,  0.714363  ],
       [-0.21702397,  0.17537922, -1.7506346 ,  0.2752878 ,  0.35554174],
       [ 0.32294512,  1.1343619 , -0.34395158,  0.05015294,  0.14216104]],
      dtype=float32)>

### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [24]:
prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 101]]

prime_tensor = tf.constant(prime, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Tampilkan dimensi dari kedua variable tersebut

In [25]:
#random tensor
random_tensor.shape
type(random_tensor)

tensorflow.python.framework.ops.EagerTensor

In [26]:
#prime tensor
prime_tensor.shape
type(prime_tensor)

tensorflow.python.framework.ops.EagerTensor

### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [27]:
# penammbahan
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.5965071,   2.0966878,   6.0288563,   6.517938 ,  11.903145 ],
       [ 13.56279  ,  16.914282 ,  19.615637 ,  25.387405 ,  30.146547 ],
       [ 30.639833 ,  38.135563 ,  42.333508 ,  43.328663 ,  46.816776 ],
       [ 53.285183 ,  58.270626 ,  60.867348 ,  71.41402  ,  71.98705  ],
       [ 79.32825  ,  83.22019  ,  88.60281  ,  95.61219  , 100.501114 ]],
      dtype=float32)>

In [28]:
#pengurangan
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -3.403493 ,   -3.9033122,   -3.971144 ,   -7.482062 ,
         -10.096855 ],
       [ -12.43721  ,  -17.085718 ,  -18.384363 ,  -20.612595 ,
         -27.853453 ],
       [ -31.360167 ,  -35.864437 ,  -39.666492 ,  -42.671337 ,
         -47.183224 ],
       [ -52.714817 ,  -59.729374 ,  -61.132652 ,  -70.58598  ,
         -74.01295  ],
       [ -78.67175  ,  -82.77981  ,  -89.39719  ,  -98.38781  ,
        -101.498886 ]], dtype=float32)>

In [29]:
#perkalian
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -2.8069859,   -2.7099366,    5.1442804,   -3.374434 ,
           9.934593 ],
       [   7.3162713,   -1.4572   ,   11.69711  ,   54.910336 ,
          33.24987  ],
       [ -11.165169 ,   42.01582  ,   54.67376  ,   14.132422 ,
          -8.611505 ],
       [  15.114646 ,  -43.033115 ,   -8.091684 ,   29.395079 ,
         -73.944916 ],
       [  25.93129  ,   18.276056 ,  -35.3493   , -134.61789  ,
         -50.38766  ]], dtype=float32)>

In [30]:
#pembagian
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.70174646, -0.30110407,  0.20577121, -0.068866  ,  0.08210408],
       [ 0.04329155, -0.00504221,  0.03240197,  0.10380025,  0.03953611],
       [-0.01161828,  0.03069088,  0.03252454,  0.00764328, -0.00389837],
       [ 0.00538079, -0.01236229, -0.0021746 ,  0.0058312 , -0.01387595],
       [ 0.00415499,  0.00265293, -0.00446273, -0.01430735, -0.00493948]],
      dtype=float32)>

In [31]:
#pangkat
tf.pow(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[3.7801284e-01, 3.7068972e-01, 5.2376866e+00, 3.9139056e-01,
        8.7202396e+00],
       [4.2356133e+00, 7.8438413e-01, 6.1270084e+00, 1.7823666e+03,
        4.7501629e+01],
       [2.9030943e-01, 6.0365849e+01, 1.4146777e+02, 3.4423685e+00,
        4.9389243e-01],
       [3.1026475e+00, 5.1095791e-02, 5.7966220e-01, 5.8404875e+00,
        1.2958600e-02],
       [4.1964788e+00, 2.6458697e+00, 1.6816482e-01, 1.7487661e-03,
        1.0001582e-01]], dtype=float32)>

In [32]:
#maximum
tf.math.maximum(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

In [33]:
#minimum
tf.math.minimum(prime_tensor,random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.4034929 , -0.9033122 ,  1.028856  , -0.48206198,  0.90314484],
       [ 0.5627901 , -0.08571765,  0.61563736,  2.3874059 ,  1.1465473 ],
       [-0.36016673,  1.1355627 ,  1.3335063 ,  0.328661  , -0.1832235 ],
       [ 0.285182  , -0.7293748 , -0.13265057,  0.4140152 , -1.0129441 ],
       [ 0.32824418,  0.22019346, -0.39718315, -1.3878133 , -0.49888772]],
      dtype=float32)>

### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [34]:
#max
tf.reduce_max(random_tensor).numpy()

2.3874059

In [35]:
#min
tf.reduce_min(random_tensor).numpy()

-1.4034929

### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [39]:
#kolom = 0
tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.4034929e+00, -9.0331221e-01,  1.0288560e+00, -4.8206198e-01,
         9.0314484e-01],
       [ 5.6279010e-01, -8.5717648e-02,  6.1563736e-01,  2.3874059e+00,
         1.1465473e+00],
       [-3.6016673e-01,  1.1355627e+00,  1.3335063e+00,  3.2866099e-01,
        -1.8322350e-01],
       [ 2.8518200e-01, -7.2937483e-01, -1.3265057e-01,  4.1401520e-01,
        -1.0129441e+00],
       [ 3.2824418e-01,  2.2019346e-01, -3.9718315e-01, -1.3878133e+00,
        -4.9888772e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
      

In [47]:
#kolom = 0
tf.concat([random_tensor, prime_tensor], axis=1)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-2.4479930e-01,  1.2106918e+00, -4.0403688e-01, -6.1715867e-02,
        -1.3918667e+00,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 1.0384767e+00,  5.2305520e-01,  1.4361411e+00, -5.7494342e-01,
        -3.8720694e-01,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [-1.4719977e+00,  7.3088956e-01, -1.4838583e+00,  1.2816611e-01,
         1.3089405e+00,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [ 1.4885427e+00,  1.5170054e-01,  2.7196124e-01,  5.8594680e-01,
        -2.4272859e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-5.1163554e-01,  1.4853485e+00, -9.9505407e-01, -1.1164328e+00,
        -1.0387598e-02,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0100000e+02]], dtype=float32)>

### Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [48]:
tf.sort(random_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.2106918 , -0.06171587, -0.2447993 , -0.40403688, -1.3918667 ],
       [ 1.4361411 ,  1.0384767 ,  0.5230552 , -0.38720694, -0.5749434 ],
       [ 1.3089405 ,  0.73088956,  0.12816611, -1.4719977 , -1.4838583 ],
       [ 1.4885427 ,  0.5859468 ,  0.27196124,  0.15170054, -2.427286  ],
       [ 1.4853485 , -0.0103876 , -0.51163554, -0.99505407, -1.1164328 ]],
      dtype=float32)>

In [49]:
tf.sort(prime_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)>